baseurl                 = "https://www.bicyclewatercooler.com/"
relativeurls            = true
DefaultContentLanguage  = "en"
title                    = "Bicycle Water Cooler"
theme                   = "persian"
preserveTaxonomyNames   = true
paginate                = 7 # odd number works best here
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = [""]
enableRobotsTXT         = true
canonifyURLs            = true
# disqusShortname         = "bicyclewatercooler"
# disqus_url              = "bicyclewatercooler.com"

[taxonomies]
  tag = 'tags'

[outputFormats]
    [outputFormats.SearchIndex]
    mediaType   = "application/json"
    baseName    = "search"

[outputs]
    home = ["html", "json", "RSS", "SearchIndex"]

[permalinks]
  blog = "/:section/:year/:month/:title/"
  travel = "/:section/:year/:title/"
  reviews = "/:section/:title/"

[params]
  search            = true # enables search, from Persian theme
  searchJSONFile    = "search.json"
  siteName          = "Bicycle Water Cooler"
  logo              = "/img/main/bwc_350x116_light.png"
  logo_dark         = "/img/main/bwc_350x116_dark.png"
  oglogo            = "/img/main/bwc_oglogo.jpg"
  # disableDarkMode = true
  #logoAlt          = "Bicycle Water Cooler | Join the virtual water cooler conversation about bikes, travel, and tech."
  logoAlt           = "Your online blog resource for bikes, travel, and tech. Come join the conversation."
  ga_analytics      = "UA-172930899-1" # added myself
  google_analitycs_id = "UA-172930899-1" # used in footer.html, pulled from Persian theme
  amzn_associate_id = "bicyclewate08-20"
  mainSections      = ["blog", "travel", "reviews", "tech"]
  copyright         = "James Clarke"
  customCss         = ["css/custom.css"] # come back to this? implement grid for bikebox pics

  # Add additional section names to mainSections to include posts from
  # those sections on the homepage.
  enableCDN             = false

  # Loads CSS and JavaScript files. The variable is an array so that you can load
  # multiple/additional files if necessary. The standard theme files can be loaded
  # by adding the value, "default". Default includes the add-on.css and and-on.js.
  # Example: ["default", "/path/to/file"]
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  # Sets options for highlight.js
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  # Sets where "View More Posts" links to
  viewMorePostsLink     = "/blog/"
  # Activate Estimated Reading Times, which appear in the post headers
  readingTime           = true
  # Sets which Social Share links appear in posts.
  # Options are twitter, facebook, reddit, linkedin, pinterest, email
  socialShare           = ["facebook", "reddit", "linkedin", "email"]

  description = "Welcome to the Bicycle Water Cooler, your online water cooler conversation about all things cycling. Come join the conversation!"

  [params.meta]
    description         = "Bicycle Water Cooler Blog | Biking, Travel, Tech, Reviews"
    # Sets the meta tag author
    author              = "James Clarke"
    keywords            = [
      "bicycle water cooler",
      "cycling",
      "cycling blog",
      "cycling blogs for beginners",
      "cycling tips for beginners",
      "beginning cycling",
      "bike ride blog",
      "bay area bike",
      "traveling with bike",
      "cycling travel",
      "cycling trips",
      "bike routes",
      "cycling technology",
      "bike tech",
      "cycling product news",
      "cycling product research",
      "cycling product reviews",
      "bike product reviews",
      "cycling events",
      "bike events",
      "bike event reviews",
      ]

[menu]
  # Sets the menu items in the navigation bar
  # Identifier prepends a Font Awesome icon to the menu item
  # [[menu.main]]
  #   name              = "Home"
  #   identifier        = "home"
  #   url               = "/"
  #   pre               = "<i class='fa fa-home'></i>"
  #   weight            = 1

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Travel"
    identifier        = "travel"
    url               = "/travel/"
    pre               = "<i class='fas fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Reviews"
    identifier        = "reviews"
    url               = "/reviews/"
    pre               = "<i class='fas fa-bicycle'></i>"
    weight            = 4

  [[menu.main]]
    name              = "Tech"
    identifier        = "tech"
    url               = "/tech/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 6

  # [[menu.main]]
  #   name              = "Contact"
  #   identifier        = "contact"
  #   url               = "/contact/"
  #   pre               = "<i class='far fa-envelope'></i>"
  #   weight            = 6

[Languages]
  # Each language has its own menu.
  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Networks (removed several that were not needed)
  strava                = "2228883"
  instagram             = "bicyclewatercooler"
  linkedin              = "jmclarke10"
  linkedin_company      = ""
  facebook              = "tmswfrk"
  googleplus            = ""
  reddit                = "tmswfrk"
  quora                 = ""
  youtube               = "channel/UCwqt0Tgyv4MaAeccyH4I7Pg"
  github                = "tmswfrk/bicycle-water-cooler"
  gitlab                = ""
  stackoverflow         = "" # User Number
  # Email
  email                 = "bicyclewatercooler@gmail.com"

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/css/imggrid.css"
[[params.plugins.css]]
link = "plugins/css/custom.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"