baseurl                 = "https://localhost:1313/"
DefaultContentLanguage  = "en"
title                   = "Bicycle Water Cooler"
theme                   = "hugo-future-imperfect-slim"
preserveTaxonomyNames   = true
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = [""]

[params]
  # Add additional section names to mainSections to include posts from
  # those sections on the homepage.
  enableCDN             = false

  # Loads CSS and JavaScript files. The variable is an array so that you can load
  # multiple/additional files if necessary. The standard theme files can be loaded
  # by adding the value, "default". Default includes the add-on.css and and-on.js.
  # Example: ["default", "/path/to/file"]
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  # Sets options for highlight.js
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  # Sets where "View More Posts" links to
  viewMorePostsLink     = "/posts/"
  # Activate Estimated Reading Times, which appear in the post headers
  readingTime           = true
  # Sets which Social Share links appear in posts.
  # Options are twitter, facebook, reddit, linkedin, pinterest, email
  socialShare           = ["facebook", "reddit", "linkedin", "email"]

  [params.meta]
    # Sets the meta tag description
    description         = "A website to discuss all things Bicycle related."
    # Sets the meta tag author
    author              = "James Clarke"
    # If you would like to add more comprehensive favicon support passed root
    # directory favicon.ico, utlize this funtion. It is recommened to use
    # https://realfavicongenerator.net to generate your icons as that is the basis
    # for the theme's naming.
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff" # Copy from the https://realfavicongenerator.net
    iOSColor            = "#ffffff" # Copy from the https://realfavicongenerator.net

  [params.header]
    # Sets the navbarTitle that appears in the top left of the navigation bar
    navbarTitle         = "The Bicycle Water Cooler"
    # Sets navbarTitle to match the section of the website
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
  [params.intro]
    header                = "The Bicycle Water Cooler"
    paragraph             = "Biking around the world, and talking about it one water cooler conversation at a time."
    rssIntro              = true
    socialIntro           = true
    # You may not want to display a long intro above content in the
    # single column layout used on smaller screens.
    hideWhenSingleColumn  = false
    # But you may want to always display the intro on the homepage.
    alwaysOnHomepage      = false

    # This appears at the top of the sidebar above params.intro.header.
    # A width of less than 100px is recommended from a design perspective.
    [params.intro.pic]
      src                 = "/img/main/bwc.jpg"
      # Masks image in a certain shape. Supported are circle, triangle, diamond, and hexagon.
      shape               = "circle"
      width               = ""
      alt                 = "Hugo Future Imperfect Slim"

  [params.sidebar]
    about               = "A techie from southern CA, living in San Francisco, obsessed with all things tech and bike related."
    # Sets the number of recent posts to show in the sidebar. The default value is 5.
    postAmount          = 5
    # set to show or to hide categories in the sidebar
    categories          = true
    # Sets Categories to sort by number of posts instead of alphabetical
    categoriesByCount   = true

  [params.footer]
    # Sets RSS icons to appear on the sidebar with the social media buttons
    rssFooter           = true
    # Sets Social Media icons to appear on the sidebar
    socialFooter        = true

  # Disqus will take priority over Staticman (github.com/eduardoboucas/staticman)
  # due to its ease of use. Feel free to check out both and decide which you would
  # prefer to use. See staticman.yml for additional settings.
  [params.staticman]
    # If using GitHub, go to https://github.com/apps/staticman-net
    # If using GitLab, just add the GitLab bot, NO need to hit `/connect/v3/...`
    enabled             = false
    api                 = ""  # without trailing slash, defaults to "staticman3.herokuapp.com"
    gitProvider         = "github"  # either "github" or "gitlab"
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      # Both keys must be present to enable recaptcha
      siteKey           = "" # Site Key
      encryptedKey      = ""

[menu]
  # Sets the menu items in the navigation bar
  # Identifier prepends a Font Awesome icon to the menu item
  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/posts/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

[Languages]
  # Each language has its own menu.
  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.fr]
    LanguageCode        = "fr"
    LanguageName        = "Français"
    title               = "Hugo Future Imperfect Slim en français"
    description         = "Un thème par HTML5 UP, porté par Julio Pescador. Simplifié et amélioré par Patrick Collins. Multilingue par StatnMap. Propulsé par Hugo."
    weight              = 2

    [[Languages.fr.menu.main]]
      name              = "Accueil"
      identifier        = "home"
      url               = "/"
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.fr.menu.main]]
      name              = "About"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.fr.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.fr.menu.main]]
      name              = "Catégories"
      identifier        = "categories"
      url               = "/categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5

    [[Languages.fr.menu.main]]
      name              = "Contact"
      identifier        = "contact"
      url               = "/contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

  [Languages.pl]
    LanguageCode        = "pl"
    LanguageName        = "Polski"
    title               = "Hugo Future Imperfect Slim po polsku"
    description         = "Motyw HTML5 UP, przeniesiony przez Julio Pescadora i wzbogacony przez Patricka Collinsa. Wielojęzyczny przez StatnMap. Zasilany przez Hugo."
    weight              = 2

    [[Languages.pl.menu.main]]
      name              = "Home"
      identifier        = "home"
      url               = "/"
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.pl.menu.main]]
      name              = "O mnie"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.pl.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.pl.menu.main]]
      name              = "Kategorie"
      identifier        = "categories"
      url               = "/categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5

    [[Languages.pl.menu.main]]
      name              = "Kontakt"
      identifier        = "contact"
      url               = "/contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

  [Languages.pt]
    LanguageCode        = "pt"
    LanguageName        = "Português"
    title               = "Hugo Future Imperfect Slim em português"
    description         = "Um tema do HTML5 UP, portado por Julio Pescadora e reduzido por Patrick Collins. Multilíngue por StatnMap. Feito com Hugo."
    weight              = 4

    [[Languages.pt.menu.main]]
      name              = "Início"
      identifier        = "home"
      url               = "/"
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.pt.menu.main]]
      name              = "Sobre"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.pt.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.pt.menu.main]]
      name              = "Categorias"
      identifier        = "categories"
      url               = "/categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5

    [[Languages.pt.menu.main]]
      name              = "Contato"
      identifier        = "contact"
      url               = "/contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

  [Languages.de]
    LanguageCode        = "de"
    LanguageName        = "Deutsche"
    weight              = 5

  [Languages.es]
    LanguageCode        = "es"
    LanguageName        = "Española"
    weight              = 6

  [Languages.zh-CN]
    LanguageCode        = "zh-CN"
    LanguageName        = "中文"
    weight              = 7

  [Languages.zh-TW]
    LanguageCode        = "zh-TW"
    LanguageName        = "中文"
    weight              = 8

  [Languages.ja]
    LanguageCode        = "ja"
    LanguageName        = "日本語"
    weight              = 9

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Networks (removed several that were not needed)
  strava                = "2228883"
  instagram             = "tmswfrk"
  linkedin              = "jmclarke10"
  linkedin_company      = ""
  facebook              = "tmswfrk"
  googleplus            = ""
  reddit                = "tmswfrk"
  quora                 = ""
  youtube               = "channel/UCwqt0Tgyv4MaAeccyH4I7Pg"
  github                = "tmswfrk/bicycle-water-cooler"
  gitlab                = ""
  stackoverflow         = "" # User Number
  # Email
  email                 = "tmswfrk@gmail.com"
